# Your database settings
database:
  # Currently supported providers:
  # - SQLite
  provider: SQLite
  # Only used when selecting SQLite
  file: sqlite.db
  # Only used when using a non file-based SQL Database
  database-name: minecraft_nick

nicknames:
  # Currently supported providers:
  # - json-file
  provider: json-file
