name: Nick
api-version: 1.16
authors:
  - NyCode
main: de.nycode.nickplugin.NickPlugin
version: @version@
database: true

permissions:
  nick.use:
    default: false
    description: Allows the usage of the /nick command

commands:
  nick:
    aliases:
      - nickname