name: Nick
api-version: 1.16
authors:
  - NyCode
main: de.nycode.nickplugin.NickPlugin
version: @version@
database: true
depend:
  - ProtocolLib

permissions:
  nick.use:
    default: false
    description: Allows the usage of the /nick command
  nick.config:
    default: false
    description: Allows to configure the plugin with

commands:
  nick:
    aliases:
      - nickname
    permission: nick.use
  nickconfig:
    aliases: [nc]
    permission: nick.config